export const sliderData = [
  {
    id: 1,
    img: "https://i.ibb.co/Lpg0VXt/pexels-kate-gundareva-8676761-removebg-preview.png",
    title: "AUTUMN LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  },
  {
    id: 2,
    img: "https://i.ibb.co/h1bC6BD/pexels-photo-1496647-removebg-preview.png",
    title: "SUMMER COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  },
  {
    id: 3,
    img: "https://i.ibb.co/0sWwDGK/pexels-5010662-removebg-preview.png",
    title: "WINTER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/9771509/pexels-photo-9771509.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "VIEW ALL",
    category: "",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2845475/pexels-photo-2845475.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    title: "SHIRT STYLE!",
    category: "shirts",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/6578757/pexels-photo-6578757.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    title: "LOUNGEWEAR LOVE",
    category: "unisex",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
    category: "jacket",
  },
  {
    id: 5,
    img: "https://i.ibb.co/3r0m60d/pexels-cottonbro-6626754.jpg",
    title: " FANCY PANTS",
    category: "pant",
  },
  {
    id: 6,
    img: "https://i.ibb.co/8DQNnBD/pexels-cottonbro-6474585.jpg",
    title: "SASSY SUITS!",
    category: "suit",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/7194641/pexels-photo-7194641.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    title: "WOMENSWEAR",
    category: "women",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/1851261/pexels-photo-1851261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    title: "CLASSY MENSWEAR",
    category: "men",
  },
];

export const productDataDetail = [
  {
    _id: "1",
    title: "Check Jacket",
    src: [
      "https://i.ibb.co/RzC19Y2/zara-Green-Jacket1.jpg",
      "https://i.ibb.co/njKR6hY/zara-Green-Jacket2.jpg",
      "https://i.ibb.co/F4NRZsP/zara-Green-Jacket3.jpg",
    ],
    desc: "Collared jacket with long sleeves and buttoned cuffs. Featuring patch pockets at the hip and a button-up front.",
    price: "7990",
    delivery: "products are usually delivered in 3-7 days.",

    colors: ["navyblue"],
    size: ["S", "M", "L"],
    count: 1,
  },
];

export const productsData = [
  {
    _id: "1",
    title: "CHECK JACKET",
    img: [
      "https://i.ibb.co/RzC19Y2/zara-Green-Jacket1.jpg",
      "https://i.ibb.co/njKR6hY/zara-Green-Jacket2.jpg",
      "https://i.ibb.co/F4NRZsP/zara-Green-Jacket3.jpg",
    ],
    desc: "Collared jacket with long sleeves and buttoned cuffs. Featuring patch pockets at the hip and a button-up front.",
    price: "7990",
    categories: ["men", "jacket"],
    colors: ["navyblue"],
    sizes: ["S", "M", "L"],
    count: 1,
  },
  {
    _id: "2",
    title: "FAUX LEATHER BIKER JACKET",
    img: [
      "https://i.ibb.co/0272FXc/biker-Jacket1.webp",
      "https://i.ibb.co/cTB8fYT/biker-Jacket2.webp",
      "https://i.ibb.co/SQ1KkK9/biker-Jacket3.jpg",
    ],
    desc: "Jacket featuring a lapel collar with snap buttons. Long sleeves with zip cuffs. Front zip pockets on the chest and hip. Inside pocket. Asymmetric metal zip-up fastening",
    price: "5990",
    categories: ["men", "women", "unisex", "jacket"],
    colors: ["black"],
    sizes: ["S", "M", "L"],
    count: 3,
  },
  {
    _id: "3",
    title: "PRINTED KNIT OVERSHIRT",
    img: [
      "https://i.ibb.co/gD6sKnZ/printed-Knit-Over-Shirt.webp",
      "https://i.ibb.co/dfYBBQc/printed-Knit-Over-Shirt2.jpg",
      "https://i.ibb.co/Q9GWPD3/printed-Knit-Over-Shirt3.jpg",
    ],
    desc: "Knit collared overshirt with long sleeves and a button-up front.",
    price: "4990",
    categories: ["women", "jacket"],
    colors: ["black"],
    sizes: ["S", "M", "L"],
    count: 3,
  },

  {
    _id: "4",
    title: "UNICORN SWEATSHIRT",
    img: [
      "https://i.ibb.co/wpd8cJb/product-Image1.jpg",
      "https://i.ibb.co/JjSQ4xB/product-Image2.jpg",
      "https://i.ibb.co/dt859xQ/Product-Image3.jpg",
      "https://i.ibb.co/j3QL33G/product-Image4.jpg",
    ],
    desc: "The most comfy style for your little one! This adorable hooded sweatshirt is a must have for the season. Adorable prints detailing make it super stylish and the soft fabric makes it a comfortable choice.",
    price: "2300",
    categories: ["kids"],
    sizes: ["S", "M", "L"],
    colors: ["red", "black", "crimson", "teal"],
  },
  {
    _id: "5",
    title: "CROPPED SOFT OVERSHIRT",
    img: [
      "https://i.ibb.co/LdWN0DM/cropped-Soft-Overshirt1.webp",
      "https://i.ibb.co/jv3GxP4/cropped-Soft-Overshirt2.webp",
    ],
    desc: "Collared overshirt with long sleeves. Featuring front patch pockets with flaps and contrast button fastening at the front",
    price: "2,990",
    categories: ["women", "jacket"],
    sizes: ["S", "M", "L"],
    colors: ["beige"],
  },
  {
    _id: "6",
    title: "TEXTURED OVERSHIRT",
    img: [
      "https://i.ibb.co/2PT8zRY/womentextured1.webp",
      "https://i.ibb.co/0rzD5sS/womentextured2.webp",
      "https://i.ibb.co/8zfYRdF/womentextured3.jpg",
    ],
    desc: "Collared overshirt with cuffed long sleeves. Front patch pockets. Front fastening with rhinestone buttons",
    price: "5,590",
    categories: ["women", "jacket"],
    sizes: ["S", "M", "L"],
    colors: ["blue", "white"],
  },
  {
    _id: "7",
    title: "SATIN SHIRT",
    img: [
      "https://i.ibb.co/0tB5kTB/satin-Shirt1.webp",
      "https://i.ibb.co/PsL5ffV/satin-Shirt2.webp",
      "https://i.ibb.co/G2xHwNg/satin-Shirt3.webp",
    ],
    desc: "Collared satin shirt featuring long sleeves with cuffs. Features an asymmetric hem and a button-up front",
    price: "2,990",
    categories: ["women", "shirt"],
    sizes: ["S", "M", "L"],
    colors: ["lime", "blue", "orange"],
  },
  {
    _id: "8",
    title: "GATHERED SHIRT",
    img: [
      "https://i.ibb.co/vhLQHgN/gathered-Shirt1.webp",
      "https://i.ibb.co/09LFxkN/gathered-Shirt2.webp",
      "https://i.ibb.co/rZkKWLx/gathered-Shirt3.webp",
    ],
    desc: "Shirt featuring a johnny collar and long sleeves with a golden button. Gathered detail on the front and invisible side zip fastening",
    price: "2,890",
    categories: ["women", "shirt"],
    sizes: ["S", "M", "L"],
    colors: ["lightbrown"],
  },
  {
    _id: "9",
    title: "ABSTRACT PRINT SHIRT",
    img: [
      "https://i.ibb.co/LkgwrK5/Abstract-Print-Shirt1.jpg",
      "https://i.ibb.co/zRtDWwK/Abstract-Print-Shirt2.jpg",
      "https://i.ibb.co/SQBxHn6/Abstract-Print-Shirt3.jpg",
    ],
    desc: "Regular fit collared shirt featuring long sleeves with buttoned cuffs and a button-up front",
    price: "4,990",
    categories: ["men", "shirt"],
    sizes: ["S", "M", "L"],
    colors: ["black", "white"],
  },
  {
    _id: "10",
    title: "TAILORED OXFORD SHIRT",
    img: [
      "https://i.ibb.co/qnbV0qV/tailored-Oxford-Shirt1.webp",
      "https://i.ibb.co/g7SJGGG/tailored-Oxford-Shirt2.webp",
      "https://i.ibb.co/0QTC9VT/tailored-Oxford-Shirt3.jpg",
    ],
    desc: "Relaxed fit button-down collar shirt featuring long sleeves with buttoned cuffs. Chest patch pocket detail and a button-up front",
    price: "1,990",
    categories: ["men", "shirt"],
    sizes: ["S", "M", "L"],
    colors: ["skyblue", "white", "bottlegreen", "navyblue"],
  },
  {
    _id: "11",
    title: "TWIDE FIT TROUSERS",
    img: [
      "https://i.ibb.co/L6tBrNQ/wide-Fit-Trouser1.jpg",
      "https://i.ibb.co/Bt9p7PH/wide-Fit-Trouser2.jpg",
      "https://i.ibb.co/HBFkKzr/wide-Fit-Trouser3.jpg",
      "https://i.ibb.co/340mhLC/wide-Fit-Trouser4.jpg",
    ],
    desc: "Wide fit trousers with an elastic waistband, front pleat detail, front pockets and double welt rear pockets. Front zip fly and top button fastening.",
    price: "3,990",
    categories: ["men", "trouser", "pant"],
    sizes: ["S", "M", "L"],
    colors: ["brown"],
  },
  {
    _id: "12",
    title: "STRAIGHT FIT JEANS",
    img: [
      "https://i.ibb.co/mB1R0Nh/men-Jeans1.webp",
      "https://i.ibb.co/r0G31Hm/men-Jeans2.jpg",
      "https://i.ibb.co/BwJtcS1/men-Jeans3.jpg",
    ],
    desc: "Straight fit jeans with a five-pocket design. Faded effect. Front button fastening.",
    price: "2,990",
    categories: ["men", "jeans", "pant"],
    sizes: ["S", "M", "L"],
    colors: ["gray"],
  },
  {
    _id: "13",
    title: "JACQUARD TROUSERS",
    img: [
      "https://i.ibb.co/k2WMDMT/jacquard-Trouser1.webp",
      "https://i.ibb.co/VqzXmpD/jacquard-Trouser2.webp",
      "https://i.ibb.co/wYYCth4/jacquard-Trouser3.jpg",
    ],
    desc: "High-waist trousers with an elastic waistband.",
    price: "1,990",
    categories: ["women", "trouser", "pant"],
    sizes: ["S", "M", "L"],
    colors: ["green", "blue"],
  },
  {
    _id: "14",
    title: "FAUX LEATHER MARINE TROUSERS",
    img: [
      "https://i.ibb.co/bB4JpFv/marine-Straight1.webp",
      "https://i.ibb.co/710sd4d/marine-Staight2.webp",
      "https://i.ibb.co/8Xpkqc4/marine-Staight3.jpg",
    ],
    desc: "Faux leather high-waist trousers with a wide-leg design, front and rear patch pockets and seamless hems. Zip fly and metal top button fastening.",
    price: "2,990",
    categories: ["women", "trouser", "pant"],
    sizes: ["S", "M", "L"],
    colors: ["black"],
  },
  {
    _id: "15",
    title: "DOUBLE-BREASTED SUIT BLAZER",
    img: [
      "https://i.ibb.co/s1KQMzT/double-Breasted-Blazer1.webp",
      "https://i.ibb.co/GHQp49H/double-Breasted-Blazer2.webp",
      "https://i.ibb.co/VLKzpHZ/double-Breasted-Blazer3.jpg",
    ],
    desc: "Blazer with a peak lapel collar and long sleeves with buttons at the cuffs. Hip welt pockets and an inside pocket. Central back vent at the hem. Double-breasted buttoned front.",
    price: "8,990",
    categories: ["men", "suit", "blazer"],
    sizes: ["S", "M", "L"],
    colors: ["brick"],
  },
  {
    _id: "16",
    title: "WIDE LAPEL SUIT BLAZER",
    img: [
      "https://i.ibb.co/rwnxCBb/lapel-Wide-Suit1.webp",
      "https://i.ibb.co/wK1JrhG/lapel-Wide-Suit2.webp",
      "https://i.ibb.co/8Dg24Th/lapel-Wide-Suit3.jpg",
    ],
    desc: "Blazer featuring a wide peak lapel collar and long sleeves with buttoned cuffs. Hip patch pockets and an inside pocket. Central back vent at the hem. Front button fastening.",
    price: "8,990",
    categories: ["men", "suit", "blazer"],
    sizes: ["S", "M", "L"],
    colors: ["camel"],
  },
  {
    _id: "17",
    title: "TEXTURED CROPPED BLAZER",
    img: [
      "https://i.ibb.co/MR9msmp/cropped-Blazer1.webp",
      "https://i.ibb.co/zPKk3vF/cropped-Blazer2.jpg",
      "https://i.ibb.co/QrzkXLM/cropped-Blazer3.webp",
    ],
    desc: "Cropped blazer featuring a lapel collar and V-neck. Long sleeves with shoulder pads. Metal button fastening at the front.",
    price: "4,990",
    categories: ["women", "suit", "blazer"],
    sizes: ["S", "M", "L"],
    colors: ["black", "red", "blue", "yellow"],
  },

  {
    _id: "18",
    title: "UNISEX TEXTURED T-SHIRT",
    img: [
      "https://i.ibb.co/r6mnFRx/unisex-Tshirt1.webp",
      "https://i.ibb.co/vjK7tVq/unisex-Tshirt2.webp",
      "https://i.ibb.co/VWW8MNB/unisex-Tshirt3.webp",
    ],
    desc: "Short sleeve T-shirt with a round neckline.",
    price: "1,790",
    categories: ["women", "men", "unisex", "tshirt", "lounge"],
    sizes: ["S", "M", "L"],
    colors: ["white", "black", "yellow"],
  },
  {
    _id: "19",
    title: "UKNIT HIGH NECK T-SHIRT",
    img: [
      "https://i.ibb.co/QnZr2K2/High-Neck-Knit1.jpg",
      "https://i.ibb.co/747FLJL/High-Neck-Knit2.jpg",
      "https://i.ibb.co/Y3rgjhT/High-Neck-Knit3.jpg",
    ],
    desc: "Short sleeve T-shirt with a round neckline.",
    price: "1,790",
    categories: ["women", "men", "unisex", "tshirt", "lounge"],
    sizes: ["S", "M", "L"],
    colors: ["lightkhaki", "white", "black", "yellow"],
  },
];
